### ISSUE TITLE
Insta Scraping: like folder not created

### ISSUE THREAD

**Issue by lucasdurand** [relytb/tinder#1]
Running through a fresh install, running script from root directory

When running through tutorial, the 'like' folder is not created before insta_scrape.py attempts to read it's contents:

```
File "insta_scrape.py", line 63, in <module>
    seen = getSeen()
  File "insta_scrape.py", line 19, in getSeen
bash: syntax error near unexpected token `most'
    entries = os.listdir(SAMPLE_LIKES_DIR)
FileNotFoundError: [Errno 2] No such file or directory: 'like'
```

**Comment by lucasdurand** [comment]
Likewise for "nope"

```
Traceback (most recent call last):
  File "auto_swipe.py", line 38, in <module>
    setupDicts()
  File "auto_swipe.py", line 23, in setupDicts
    nopes = load(SAMPLE_NOPES_DIR)
  File "/home/durand/dev/tinder/knn.py", line 43, in load
    entries = os.listdir(img_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'nope'
```

**Comment by relytb** [comment]
1) Put a dummy file in directories in the repo to make sure they exist
2) check/create them in a centralized location (probably constants.py)
3) check/create them everywhere they're read

I'm leaning towards 1

**Comment by lucasdurand** [comment]
1!

**Comment by lucasdurand** [comment]
But some of the other logic breaks if they aren't there. 
i.e. saving photos into the *_swiped folders in DEBUG mode silently fails when the dirs aren't there. You end up streaming through photos with nothing to show for it.

**Comment by relytb** [comment]
Yeah it was a mistake to create those dynamically, I think during the exploratory phase it made things easier to have the code create them bc I was constantly deleting the directories instead of just wiping them clean
