### ISSUE TITLE
Store swipe votes of NN

### ISSUE THREAD

**Issue by lucasdurand** [relytb/tinder#4]
For future updates, it would be useful to store information on decision-making in swipes.

**What are the profile names of the k-NN and how did they vote?**
This will be useful to look back on decisions and see why, perhaps identify mislabelled/troublesome images

**Which descriptors are going into decisions?**
Guessing this will be more difficult, but logging which elements of the facial recognition are triggering events will allow for more detailed analysis

**Comment by relytb** [comment]
Yep, this is something I'd noted as well. Do you think this should exist as a part of debug mode? Or is there value in having a separate flag so that you can see why you matched with someone for real? It would generate a lot of extra files (or one really big one) so I'd imagine you'd want it off at some point

**Comment by lucasdurand** [comment]
I think part I should be available for everything. I'm not up on how the facial recog descriptors work, but if we can extract some summary info from that (i.e. eyes / nose match?) I'd store that for everything. Anything more complicated should be left for debug

**Comment by relytb** [comment]
I'm thinking about setting up logging, right now if you pipe the output of auto_swipe.py to a file you can grep it by tinder ID and find out part 1. 

Could just have a log file and some utilities to extract meaningful information from it?

**Comment by relytb** [comment]
Part 2 would be good but possibly not be feasible, turning faces into feature vectors is probably a one-way operation

**Comment by relytb** [comment]
I've decided that printing to stdout is good enough
